# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da9c689f2aaed67c7ae0cd4184d1ae21897438899a3a07abb0dbf6fbbb720e92602455e935b1757287076f3e4c0bfd40eceef53c7f062f374c01b98d5295969f

test:
  secret_key_base: 825e7cbbe6cd56aaea38396e711176e062fce75d1475e2be5c245f255dfcd248a9d478d8c592b131c380c230b43f540914e52822f557100e062387b0fdaf4d3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
